spring:
  application:
    name: "configserver"
  profiles:
    #active: native
   active: git
  cloud:
    config:
      server:
        #native:
          #search-locations: "classpath:/config"
        #also we can use file
       git:
         uri: "https://github.com/Nurikjavakg/eazybytes-config-1.git"
         default-label: main
         timeout: 10
         clone-on-start: true
         force-pull: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true

encrypt:
  key: "432afda43ffgaas"

server:
  port: 8071
