services:
  accountsdb:
    image: postgres
    container_name: accountsdb
    ports:
      - "5432:5432"

    environment:
      POSTGRES_DB: "postgres"

    extends:
      file: common-config.yml
      service: microservice-db-config

  cardsdb:
    container_name: cardsdb
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: "postgres"

    extends:
      file: common-config.yml
      service: microservice-db-config

  loansdb:
    container_name: loansdb
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: "postgres"

    extends:
      file: common-config.yml
      service: microservice-db-config
  configserver:
    image: "nurik345/configserver:s7"
    container_name: configserver-ms
    ports:
      - "8071:8071"
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - eazybank
  accounts:
    image: "nurik345/accounts:s7"
    container_name: accounts-ms
    ports:
      - "9091:9090"

    environment:
      SPRING_APPLICATION_NAME: "accounts"
      SPRING_DATASOURCE_URL: "jdbc:postgresql://accountsdb:5432/accountsdb"
    depends_on:
      accountsdb:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: microservice-configserver-config

  loans:
    image: "nurik345/loans:s7"
    container_name: loans-ms
    ports:
      - "8090:8090"

    environment:
      SPRING_APPLICATION_NAME: "loans"
      SPRING_DATASOURCE_URL: "jdbc:postgresql://loansdb:5433/loansdb"
    depends_on:
      loansdb:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: microservice-configserver-config

  cards:
    image: "nurik345/cards:s7"
    container_name: cards-ms
    ports:
      - "9100:9000"

    environment:
      SPRING_APPLICATION_NAME: "cards"
      SPRING_DATASOURCE_URL: "jdbc:postgresql://cardsdb:5434/cardsdb"
    depends_on:
      cardsdb:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: microservice-configserver-config

networks:
  eazybank:
    driver: "bridge"